### PR TITLE
Added basic CosmoPower theory code.

### PR DESCRIPTION
**Pull request by HTJense**
Simple [CosmoPower](https://github.com/alessiospuriomancini/cosmopower) implementation for SOLikeT.

### CODE REVIEW

**Comment by itrharrison** [comment]
Are you okay to try and add cosmopower as an optional dependancy / extra requirement? It currently doesn’t get installed into the testing env which is why it is failing.

I think the best way to manage this is to put it in `extras_require = {‘cosmopower’ : [‘cosmopower’]}` in ‘setup.py’ and then add an extra `install extra reqs` section in the `testing.yml`.

Let me know if you need any help with that… or can think of a better way!

**Comment by itrharrison** [comment]
I added a test which compares against camb. Even if this doesn't make it into the final test suite I think it is good to have a comparison attached to the PR at least.

The result is here:
camb_cosmopower_relative_cl

I have a couple of concerns:
- The final 10 ell values in the CosmoPower Cl_tt are zero, which is what causes the rtol to shoot up.
- The rtol is O(1.e-2) for a lot of the range, which seems high to me? Looking at the CosmoPower documentation it is hard to assess this, as the plots in the paper are normalised according to sigmas for an SO-like experiment.

Pinging @alessiospuriomancini: is the rtol here what you might expect? and/or can you provide the sigma^tt_ell from the paper so we can check we are getting similar results?

**Comment by HTJense** [comment]
The highest two ells being zero is due to you passing on an `extra_args: { 'lmax' : [camb lmax] }` value, which is higher than the network's lmax. The theory code builds a zero-array up to your requested lmax (see [here](https://github.com/HTJense/SOLikeT/blob/dev-cosmopower/soliket/cosmopower.py#L51)) and then fills it out as far as it can (see [here](https://github.com/HTJense/SOLikeT/blob/dev-cosmopower/soliket/cosmopower.py#L92)), which may not be as high as you want it, causing high-ell values to be zero.

**Comment by HTJense** [comment]
With regards to the inaccuracy of the emulator: if I understand correctly this particular network was trained using class, so a small part of the error can be understood from having nonzero neutrino mass in camb by default, see camb_cosmopower_relative_cl. Comparing the network with class default parameters however, still shows some inaccuracies. From experience I know this is not a major issue for getting cosmological parameters from an MCMC - the differences are small.

**Review by itrharrison — APPROVED** [review]
Happy to merge.

**Comment by jcolinhill** [comment]
we have a much higher-precision emulator than this one, which @borisbolliet has constructed.  we can add this to SOLIkeT soon

**Comment by borisbolliet** [comment]
yep! also goes to l~10,000 and now have distances and P(k,z)

**Pull request merged**
