### PR TITLE
Fix mflike scales

### PR DESCRIPTION
**Pull request by sgiardie**
continuation of PR [#138](https://github.com/simonsobs/SOLikeT/pull/138), which was closed without updating the dataset that goes up to higher ells

### CODE REVIEW

**Review by mgerbino — APPROVED** [review]

**Comment by mgerbino** [comment]
@sgiardie, I think there might be an issue with the lmax bpws and lmax_theory. Shall we request that the lmax_theory is always strictly larger than lmax_bpws?

**Comment by sgiardie** [comment]
Ok, I am trying to figure out why this error occurs. My understanding is that CAMB computes the spectra up to lmax_theory + 100 or something like that, anyway extending the ell range with respect to the lmax indicated. So there should be no problem if both lmax of bpws and lmax_theory are 9000. But the theory spectra are computed in a slightly different way between LAT_MFLike and soliket/mflike, for example I am seeing that in soliket the theory spectra are computed in theoryforge, where I cannot find a `lmax_theory` but a [`lmax_boltzmann`](https://github.com/simonsobs/SOLikeT/blob/d6b2512fd84fca477d750549693f0c8718b7e600/soliket/mflike/theoryforge_MFLike.py#L83). Maybe using `lmax_boltzmann` forces CAMB to compute spectra up to that specific value?

**Comment by sgiardie** [comment]
I am finding how we assing the ell scale to CAMB.
We assign the ell range for the computation of `Cl` [here](https://github.com/simonsobs/SOLikeT/blob/d6b2512fd84fca477d750549693f0c8718b7e600/soliket/mflike/theoryforge_MFLike.py#L154):

>         # Be sure that CMB is computed at lmax > lmax_data (lcuts from mflike here)
>         reqs["Cl"] = {k: max(c, self.lmax_boltzmann + 1) for k, c in self.lcuts.items()}
> 

and the `self.lcuts` seems to be [passed from mflike](https://github.com/simonsobs/SOLikeT/blob/d6b2512fd84fca477d750549693f0c8718b7e600/soliket/mflike/theoryforge_MFLike.py#L144):

>     def must_provide(self, **requirements):
>             ...
>            self.lcuts = req.get("lcuts", self.lcuts)

and `lcuts` is computed like [the max between the lmax from the scales in the yaml file and the lmax in the data](https://github.com/simonsobs/SOLikeT/blob/d6b2512fd84fca477d750549693f0c8718b7e600/soliket/mflike/mflike.py#L309C1-L309C1):

>                 self.lcuts[k] = max(self.lcuts[k], scls[k][1])

So it's weird that it's not working

**Comment by mgerbino** [comment]
I don't think there is an error here, sorry, I was not clear. I get an error when I run the example notebook in mflike (sorry, I am mixing things and will move this conversation to the mflike repo now).  I'll keep this branch active until the issue is sorted out

**Pull request merged**
