### PR TITLE
win test

### PR DESCRIPTION
**Pull request by cmbant**

### CODE REVIEW

**Comment by cmbant** [comment]
@itrharrison This seems to be failing because of some bug in tox. I think it is fixed in latest tox, but tox-conda is much older. I don't know how to fix having tried three suggestions. Claude suggests a custom tox plugin, but seems over-engineered. Do we need to use conda for pyccl?

**Comment by itrharrison** [comment]
(modulo this issue) Using conda was the easiest cross-platform way of installing all our requirements. pyccl is on pip but its requirements (in particular I think compilers, cmake fftw and gsl) aren't necessarily.

Do you have a link to the bug fix in tox? Could try and contribute its fix to tox-conda.

We could try having a working installation using other package management options. Do you know what you would use in the case of windows?

**Comment by cmbant** [comment]
See [https://github.com/tox-dev/tox/pull/2391 and linked PRs.](https://github.com/tox-dev/tox/pull/2391). We don't use pyccl on windows, so that shouldn't be an issue.  pip should work for camb and most things I think. (camb now has binary wheels, so does not need gfortran to install)

**Comment by cmbant** [comment]
I guess the issue is tox-conda currently uses tox<4, so is based on quite old version. (this version pin probably likely to lead to other package version conflicts in future)

**Comment by cmbant** [comment]
The problem may have been to do with tox error reporting. With these extra changes to make only relevant tests run (and a fix or two), this now works OK.

**Review by itrharrison — APPROVED** [review]
lgtm, thanks for getting this done

**Pull request merged**
